In [171]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_diabetes

In [172]:
data = load_diabetes()
X = data.data
y = data.target
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
y[0]

151.0

In [173]:
X_train_num = np.dot(X_train,1000).astype(int)
X_test_num = np.dot(X_test,1000).astype(int)
y_train_num = y_train
y_test_num = y_test

In [174]:
print(X_train_num)

[[ 70  50  12 ...  34  27  -1]
 [ -9  50 -18 ...  71   0  19]
 [  5 -44  49 ...  -2  17 -13]
 ...
 [ 30 -44 -20 ... -39 -10  -1]
 [-12 -44 -23 ...  -2 -38 -38]
 [-92 -44  28 ... -39  -5  -1]]


In [175]:
X_train_den = np.full(X_train.shape, 1000) 
X_test_den = np.full(X_test.shape, 1000) 
y_train_den = np.ones(len(y_train))
y_test_den = np.ones(len(y_test))

In [176]:
print(X_train_den)

[[1000 1000 1000 ... 1000 1000 1000]
 [1000 1000 1000 ... 1000 1000 1000]
 [1000 1000 1000 ... 1000 1000 1000]
 ...
 [1000 1000 1000 ... 1000 1000 1000]
 [1000 1000 1000 ... 1000 1000 1000]
 [1000 1000 1000 ... 1000 1000 1000]]


In [190]:
#condensed function multiply and add matrix with numerator and denominator one row at a time
# Python Program to find the L.C.M. of two input number
from math import gcd
def compute_lcm(x, y):
   # choose the greater number 
    if (x > y):
        greater = x
    else:
        greater = y
    while(True):
        if(x==0):
            lcm = y
            break
        elif(y==0):
            lcm = x
            break
        elif((greater % x == 0) and (greater % y == 0)):
            lcm = greater
            break
        greater += 1
    return lcm
 
def subtraction(a,b,c,d):
    den = compute_lcm(b,d)
    if b ==0:
        num = c ; den = d
    elif d==0:
        num= a ; den = b
    else:    
        num = ((den/b)*a) - ((den/d)*c)
    return num,den

def add_array(a_num,a_den):
    #will work for an int array of any length
    lcm = 1;sum1 =0
    for i in a_den:
        lcm = int(lcm*i/gcd(lcm, i))
#     print(lcm)
    for i in range(len(a_num)):
        sum1 = sum1 + (a_num[i]*(a_den[i]/lcm))
        print(a_num[i],a_den[i],lcm)
        
#     print(sum1)
    return sum1,lcm

def addition(a,b,c,d):
    den = compute_lcm(b,d)
    if b ==0:
        num = c ; den = d
    elif d==0:
        num= a ; den = b
    else:    
        num = ((den/b)*a) + ((den/d)*c)
    return float(num),float(den)

def multiply(a_num,a_den,b_num, b_den):
    z_num = np.zeros(len(a_num)).astype(int)
    z_den = np.zeros(len(a_den)).astype(int)
    print(a_num,a_den)                                   
    for i in range(len(a_num)):
        z_num[i]=(a_num[i]*b_num[i])
        z_den[i]=(a_den[i]*b_den[i])
    num,den = add_array(z_num,z_den)
    print("multiplication results is",num,den) 
    return num,den
    

In [207]:
a= np.ones(3).astype(int)
b= np.ones(3).astype(int)

# x = np.asarray(a.tolist())
# print (x)

In [208]:
type(a[0])

numpy.int32

In [209]:
add_array(a,b)

1 1 1
1 1 1
1 1 1


(3.0, 1)

In [210]:
#claculate y_hat =wx+b | x is in the form a single array and w is in the form of array too
# need toc hange w into wnum and wden
def y_hat(w_num,w_den,x_num,x_den,b):
    y_hat_num = np.zeros(x_num.shape[0]).astype(int)
    y_hat_den = np.zeros(x_den.shape[0]).astype(int)
    #multiplying w and x
    for i in range(x_num.shape[0]):
        x_n = x_num[i] 
        x_d = x_den[i] 
        print(x_n,x_d,w_num,w_den)
        temp_n, temp_d = multiply(x_n,x_d,w_num,w_den)
        print("printing temporary values",temp_n,temp_d)
        y_hat_num[i],y_hat_den[i] = addition( temp_n, temp_d,b[0],b[1])          
    print("y_hat values for this iterationsa are",y_hat_num,y_hat_den)

In [211]:
# b =[1,100]
# w_n = [1,1,1,1,1,1,1,1,1,1]; w_d =[2,2,2,2,2,2,2,2,2,2]
# x_n = X_train_num[:2]; x_d = X_train_den[:2]
# y_hat(w_n,w_d,x_n,x_d,b)

In [212]:
def mse(y_hat_num,y_hat_den,y_num,y_den,n):
    num=0;den =0
    for i in range(len(y_hat_num)):
        num1,den1=subtraction(y_num[i],y_den[i],y_hat_num[i],y_hat_den[i])
        num1 = num1*num1
        den1 = den1*den1
        num,den = addition(num,den,num1,den1)
    den = den * n
    print(num,den)
#     return num,den

In [213]:
a =[2,2]
b =[3,3]
c= [1,1]
d= [2,2]
n = 2
mse(a,b,c,d,n)

2.0 72.0


In [214]:
#calculating subtraction of Y_hat Y
def y_hat_substraction(y_hat_num,y_hat_den,y_num,y_den):
    y_diff =np.zeros((y_hat_num.shape[0],2))
    for i in range(len(y_hat_num)):
        y_diff[i][0],y_diff[i][1] = subtraction(y_hat_num[i],y_hat_den[i], y_num[i], y_den[i])
    return y_diff



In [215]:
#getting delta w with respect 
def del_w(y_hat_num,y_hat_den, y_num, y_den,x_num, x_den, n):
    del_w_num = np.zeros(x_num.shape[1])
    del_w_den = np.zeros(x_num.shape[1])
    
    x_num = x_num.T
    x_den = x_den.T
    
    
    sub_num = np.zeros(len(y_hat_num))
    sub_den = np.zeros(len(y_hat_num))
    
    
    #subtracting y_hat from y
    for i in range(len(y_hat_num)):
        sub_num[i],sub_den[i] = subtraction(y_hat_num[i],y_hat_den[i],y_num[i],y_den[i])
    
    x_num = x_num.T
    x_den = x_den.T
    
    #Multiplying x with the previous result and saving in 10 arrays as there are 10 features 
    for i in range(len(del_w_num)):
        del_w_num[i],del_w_den[i] = multiply(sub_num[i],sub_den[i], x_num[i],x_den[i])
        del_w_num[i] = del_w_num*2
        del_w_den[i] = del_w_den*n
    return del_w_num,del_w_den
    

In [216]:
#getting delta b 
def delta_b(y_hat_num,y_hat_den,y_num,y_den):
    sub_num = np.zeros(len(y_hat_num))
    sub_den = np.zeros(len(y_hat_num))
    
    for i in range(len(y_hat_num)):
        sub_num[i],sub_den[i] = subtraction(y_hat_num[i],y_hat_den[i],y_num[i],y_den[i])
        sub_num[i] = sub_num[i]*2
        sub_den[i] = sub_den[i]*n
    return sub_num,sub_den

In [217]:
# get new weights and biases
def get_new_params(lr, dw_num,dw_den,db_num,db_den,w_num,w_den,b_num,b_den):
    
    for i in range(len(dw_num)):
        dw_num[i]= dw_num[i]*lr[0]
        dw_den[i]= dw_den[i]*lr[1]
   
    btemp_num = lr[0] * db_num
    btemp_den = lr[1] * db_den 

    
    for i in range(len(dw_num)):
        dw_num[i],dw_den[i] = subtraction(w_num[i],w_den[i],dw_num[i],dw_den[i]) 
    
    db_num,db_den = subtraction(b_num,b_den,btemp_num,btemp_den)
    return  dw_num,dw_den,db_num,db_den

In [218]:
# w = np.zeros((X_train.shape[1],2))
# b = np.zeros(2)
# lr = np.array([1,100])
# nw_num= np.zeros((X_train.shape[1]))
# nw_den= np.zeros((X_train.shape[1]))
# nb_num=nb_den =0
# for i in range(10000):
#     # finding y_hat 
#     y_hat_num = np.zeros(len(y_train_num))
#     y_hat_den = np.zeros(len(y_train_num))
#     for i in range(y_train_num.shape[0]):
#         y_hat_num[i], y_hat_den[i] = y_hat(w,X_train_num[i],X_train_den[i],b)

#     #get the MSE
#     n = len(y_train_num)
#     mse_num,mse_den = mse(y_hat_num,y_hat_den,y_train_num,y_train_den,n)
# #     print(mse_num,mse_den)

#     #get y_hat subtraction
#     y_hat_diff = np.zeros((len(y_train_num),2))
#     y_hat_diff =  y_hat_substraction(y_hat_num,y_hat_den,y_train_num,y_train_den)

#     #get delta_w 
#     delta_w_num,delta_w_den = delta_w(y_hat_diff,X_train_num,X_train_den,y_hat_diff.shape[0])
#     # print(delta_w_num,delta_w_den)

#     #get delta_b
#     delta_b_num,delta_b_den = delta_b(y_hat_diff)
# #     print(delta_b_num,delta_b_den)

#     #get new_delta
    
#     nw_num, nw_den,nb_num,nb_den = get_new_deltas(lr,delta_w_num,delta_w_den,delta_b_num,delta_b_den,nw_num,nw_den,nb_num,nb_den)
# print(nw_num, nw_den,nb_num,nb_den)

TypeError: y_hat() missing 1 required positional argument: 'b'