In [97]:
# need to remove the X and Y header information from the dataset
from random import seed
from random import randrange
from csv import reader
from math import sqrt
import pandas as pd
import numpy as np

In [98]:
df = pd.read_csv('insurance.csv',sep = ',')
dataset = df.to_numpy()
len(dataset)

62

In [99]:
X_data = dataset[:,0].astype(int)
y_data = dataset[:,1].astype(int)

In [100]:
s = X_data.tolist()

In [101]:
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

X_data= X_data.reshape(-1, 1)
y_data= y_data.reshape(-1, 1)

X_train = X_data[:40]
X_test = X_data[40:]
y_train = y_data[:40]
y_test = y_data[40:]

reg = LinearRegression().fit(X_train, y_train)
reg.score(X_train, y_train)

# reg.coef_
# array([1., 2.])
# reg.intercept_

pred = reg.predict(X_test)
# print(pred)
# print(y_test)

In [102]:
atrain = dataset[:40,0].astype(int).tolist()
atest = dataset[40:,0].astype(int).tolist()
btrain = dataset[:40,1].astype(int).tolist()
btest = dataset[40:,1].astype(int).tolist()

In [103]:
print(atrain,',',btrain)

[19, 13, 124, 40, 57, 23, 14, 45, 10, 5, 48, 11, 23, 7, 2, 24, 6, 3, 23, 6, 9, 9, 3, 29, 7, 4, 20, 7, 4, 0, 25, 6, 5, 22, 11, 61, 12, 4, 16, 13] , [46, 15, 422, 119, 170, 56, 77, 214, 65, 20, 248, 23, 39, 48, 6, 134, 50, 4, 113, 14, 48, 52, 13, 103, 77, 11, 98, 27, 38, 0, 69, 14, 40, 161, 57, 217, 58, 12, 59, 89]


In [104]:
B0 = 21
B1 = 3

In [134]:
x = dataset[40:,0].astype(int)

In [135]:
x

array([60, 41, 37, 55, 41, 11, 27,  8,  3, 17, 13, 13, 15,  8, 29, 30, 24,
        9, 31, 14, 53, 26])

In [140]:
dataset[40:,1]

array([202.4, 181.3, 152.8, 162.8,  73.4,  21.3,  92.6,  76.1,  39.9,
       142.1,  93. ,  31.9,  32.1,  55.6, 133.3, 194.5, 137.9,  87.4,
       209.8,  95.5, 244.6, 187.5])

In [136]:
pred = np.zeros(len(x)).astype(int)
pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [137]:

for i in range(len(x)):
    pred[i] = B0 + B1 * x[i]

In [138]:
pred

array([201, 144, 132, 186, 144,  54, 102,  45,  30,  72,  60,  60,  66,
        45, 108, 111,  93,  48, 114,  63, 180,  99])

In [139]:
print(btest)

[202, 181, 152, 162, 73, 21, 92, 76, 39, 142, 93, 31, 32, 55, 133, 194, 137, 87, 209, 95, 244, 187]
